name: app_quick_reports
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  android_path_provider: ^0.3.0
  animate_do: ^2.0.0
  cupertino_icons: ^1.0.2
  date_format: ^2.0.4
  device_info_plus: ^3.2.3
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.7.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  flutter_zoom_drawer: ^2.1.1
  freezed_annotation: ^0.14.1
  get: ^4.3.8
  get_storage: ^2.0.3
  intl: ^0.17.0
  logger: ^1.1.0
  lottie: ^1.2.2
  package_info_plus: ^1.4.2
  path_provider: ^2.0.9
  pdfx: ^2.0.1+2
  permission_handler: ^9.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  sentry_dio: ^6.4.0
  sentry_flutter: ^6.4.0
  skeleton_text: ^3.0.0
  # url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/img/
    - assets/lottie/
    - assets/files/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 200
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900
